# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-22 09:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenAadhar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('aadhar_uid', models.IntegerField(default=None)),
                ('verified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created'],
                'get_latest_by': 'created',
            },
        ),
        migrations.CreateModel(
            name='CitizenAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('address_line_1', models.TextField()),
                ('address_line_2', models.TextField()),
                ('landmark', models.TextField()),
                ('pin_code', models.IntegerField(blank=True)),
                ('district', models.CharField(blank=True, max_length=150, null=True)),
                ('state', models.CharField(choices=[(b'Andhra Pradesh', b'AP'), (b'Andaman and Nicobar Islands', b'AN')], max_length=100)),
                ('country', models.CharField(default='INDIA', max_length=50)),
                ('permanent', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CitizenBankDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_account_name', models.CharField(blank=True, max_length=150, null=True)),
                ('bank_account_number', models.TextField(blank=True, null=True)),
                ('bank_ifsc', models.TextField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CitizenPhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(max_length=100)),
                ('calling_code', models.CharField(default='91', max_length=10)),
                ('verified', models.BooleanField(default=False)),
                ('verification_uid', models.CharField(blank=True, max_length=10, null=True)),
                ('primary', models.BooleanField(default=False)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created'],
                'get_latest_by': 'created',
            },
        ),
        migrations.CreateModel(
            name='CitizenProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('signup_done', models.BooleanField(default=False)),
                ('signup_stage', models.IntegerField(default=1)),
                ('email_verified', models.BooleanField(default=False)),
                ('authorised', models.BooleanField(default=True)),
                ('blocked', models.BooleanField(default=False)),
                ('sex', models.CharField(choices=[(b'Male', b'M'), (b'Transgender', b'T'), (b'Female', b'F')], max_length=100)),
                ('category', models.CharField(choices=[(b'Minority', b'MN'), (b'Other Backward Classes', b'OBC'), (b'Scheduled Tribes', b'ST'), (b'Special Backwar Classes', b'SBC'), (b'Scheduled categorys', b'SC'), (b'General', b'GN')], max_length=100)),
                ('language', models.CharField(choices=[(b'English UK', b'en-uk'), (b'Hindi', b'hi'), (b'English USA', b'en-usa')], max_length=100)),
                ('pan_num', models.CharField(blank=True, max_length=10, unique=True)),
                ('occupation', models.CharField(choices=[(b'Unemployed', b'UNEMPLOYED'), (b'Private Employee', b'PRIVATE EMPLOYEE'), (b'Self Employed', b'SELF EMPLOYED'), (b'Student', b'STUDENT'), (b'Public Employee', b'PUBLIC EMPLOYEE')], max_length=100)),
                ('education_status', models.CharField(choices=[(b'10th Pass', b'MATRICULATE'), (b'12th Pass', b'INTERMEDIATE'), (b'Masters(2nd) Degree', b'POST GRADUATE'), (b'Bachelors(1st) Degree', b'GRADUATE')], max_length=100)),
                ('income_status', models.CharField(choices=[(b'Earning less than 100K per annum', b'POOR'), (b'Earning 400K - 1000K per annum', b'HIGH MIDDLE'), (b'Earning more than 1500K per annum', b'HIGH UPPER'), (b'Earning 100K - 400k per annum', b'LOW MIDDLE'), (b'Earning 1000K - 1500K per annum', b'LOW UPPER')], max_length=100)),
                ('birth', models.DateField()),
                ('death', models.DateField(blank=True, null=True)),
                ('citizen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'get_latest_by': 'created',
                'verbose_name': 'Citizen Profile',
            },
        ),
        migrations.CreateModel(
            name='GovOfficerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('authorised', models.BooleanField(default=True)),
                ('authorization_level', models.CharField(choices=[(b'Mid Level', b'1'), (b'Entry Level', b'0'), (b'Super Level', b'3'), (b'Senior Level', b'2')], max_length=20)),
                ('officer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='citizenphonenumber',
            name='citizen_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CitizenProfile'),
        ),
        migrations.AddField(
            model_name='citizenbankdetails',
            name='citizen_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CitizenProfile'),
        ),
        migrations.AddField(
            model_name='citizenaddress',
            name='citizen_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CitizenProfile'),
        ),
        migrations.AddField(
            model_name='citizenaadhar',
            name='citizen_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CitizenProfile'),
        ),
        migrations.AlterUniqueTogether(
            name='citizenphonenumber',
            unique_together=set([('citizen_profile', 'phone_number')]),
        ),
        migrations.AlterUniqueTogether(
            name='citizenaadhar',
            unique_together=set([('citizen_profile', 'aadhar_uid')]),
        ),
    ]
