# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-22 14:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20170222_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sex', models.CharField(choices=[(b'Male', b'M'), (b'Transgender', b'T'), (b'Female', b'F')], max_length=100)),
                ('category', models.CharField(choices=[(b'Minority', b'MN'), (b'Other Backward Classes', b'OBC'), (b'Scheduled Tribes', b'ST'), (b'Special Backwar Classes', b'SBC'), (b'Scheduled categorys', b'SC'), (b'General', b'GN')], max_length=100)),
                ('language', models.CharField(choices=[(b'English UK', b'en-uk'), (b'Hindi', b'hi'), (b'English USA', b'en-usa')], max_length=100)),
                ('pan_num', models.CharField(blank=True, max_length=10, unique=True)),
                ('occupation', models.CharField(choices=[(b'Unemployed', b'UNEMPLOYED'), (b'Private Employee', b'PRIVATE EMPLOYEE'), (b'Self Employed', b'SELF EMPLOYED'), (b'Student', b'STUDENT'), (b'Public Employee', b'PUBLIC EMPLOYEE')], max_length=100)),
                ('education_status', models.CharField(choices=[(b'10th Pass', b'MATRICULATE'), (b'12th Pass', b'INTERMEDIATE'), (b'Masters(2nd) Degree', b'POST GRADUATE'), (b'Bachelors(1st) Degree', b'GRADUATE')], max_length=100)),
                ('income_status', models.CharField(choices=[(b'Earning less than 100K per annum', b'POOR'), (b'Earning 400K - 1000K per annum', b'HIGH MIDDLE'), (b'Earning more than 1500K per annum', b'HIGH UPPER'), (b'Earning 100K - 400k per annum', b'LOW MIDDLE'), (b'Earning 1000K - 1500K per annum', b'LOW UPPER')], max_length=100)),
                ('birth', models.DateField()),
                ('death', models.DateField(blank=True, null=True)),
                ('citizen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'get_latest_by': 'created',
                'verbose_name': 'Citizen Details',
            },
        ),
        migrations.RemoveField(
            model_name='citizenprofile',
            name='citizen',
        ),
        migrations.AlterField(
            model_name='citizenaddress',
            name='citizen_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CitizenDetails'),
        ),
        migrations.AlterField(
            model_name='citizenbankdetails',
            name='citizen_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CitizenDetails'),
        ),
        migrations.DeleteModel(
            name='CitizenProfile',
        ),
    ]
