# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-22 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170222_2005'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CitizenBankDetails',
            new_name='CitizenBankProfile',
        ),
        migrations.RenameModel(
            old_name='CitizenDetails',
            new_name='CitizenProfile',
        ),
        migrations.AlterModelOptions(
            name='citizenprofile',
            options={'get_latest_by': 'created', 'ordering': ['-created'], 'verbose_name': 'Citizen Profile'},
        ),
    ]
