# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-22 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170222_2010'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CitizenBankProfile',
            new_name='CitizenBankDetails',
        ),
    ]
