# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-23 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20170222_2105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citizenprofile',
            options={'verbose_name': 'Citizen Profile'},
        ),
        migrations.RemoveField(
            model_name='citizenprofile',
            name='created',
        ),
        migrations.AlterField(
            model_name='citizenprofile',
            name='citizen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customauth.Citizen'),
        ),
    ]
