# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-23 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20170223_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizenaddress',
            name='current',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='citizenbankdetail',
            name='citizen_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.CitizenProfile'),
        ),
    ]
