# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-23 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20170223_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizenaddress',
            name='district',
            field=models.CharField(blank=True, default=None, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='citizenbankdetail',
            name='bank_account_name',
            field=models.CharField(blank=True, default=None, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='citizenbankdetail',
            name='bank_account_number',
            field=models.CharField(blank=True, default=None, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='citizenbankdetail',
            name='bank_ifsc',
            field=models.CharField(blank=True, default=None, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='citizenprofile',
            name='pan_num',
            field=models.CharField(blank=True, default=None, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='departmentprofile',
            name='short_name',
            field=models.CharField(blank=True, default=None, max_length=150),
            preserve_default=False,
        ),
    ]
