# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-24 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20170223_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizenaddress',
            name='pin_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='citizenaddress',
            name='state',
            field=models.CharField(blank=True, choices=[(b'Andhra Pradesh', b'AP'), (b'Uttar Pradesh', b'UP'), (b'Andaman and Nicobar Islands', b'AN')], max_length=100),
        ),
    ]
