# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-24 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20170224_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizenprofile',
            name='birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
