# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-24 21:28
from __future__ import unicode_literals

from django.db import migrations
import rajyojna.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20170225_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizenprofile',
            name='pan_num',
            field=rajyojna.fields.NullableCharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
