# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-23 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('aadhar_uid', models.IntegerField(unique=True)),
                ('email', models.EmailField(blank=True, max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('aadhar_verified', models.BooleanField(default=False)),
                ('email_verified', models.BooleanField(default=False)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('signup_done', models.BooleanField(default=False)),
                ('signup_stage', models.IntegerField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('login_count', models.IntegerField(blank=True)),
                ('update_count', models.IntegerField(blank=True)),
            ],
            options={
                'verbose_name': 'citizen',
                'verbose_name_plural': 'citizens',
            },
        ),
    ]
