# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-23 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='phone',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citizen',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
    ]
