# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-23 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0002_auto_20170223_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizen',
            name='is_authenticated',
        ),
    ]
