# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-23 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0003_remove_citizen_is_authenticated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='login_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='signup_stage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='update_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
