# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-23 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0005_auto_20170223_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
