# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-23 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0006_auto_20170223_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizen',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='citizen',
            name='last_name',
        ),
    ]
