# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-23 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0007_auto_20170223_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='is_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
