# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-23 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0008_citizen_is_authenticated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizen',
            name='is_authenticated',
        ),
        migrations.AddField(
            model_name='citizen',
            name='is_authorized',
            field=models.BooleanField(default=False),
        ),
    ]
