# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-24 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0011_auto_20170225_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='email',
            field=models.EmailField(blank=True, default=b'NA', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='username',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
