# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-24 20:30
from __future__ import unicode_literals

from django.db import migrations
import rajyojna.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0013_auto_20170225_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='email',
            field=rajyojna.fields.NullableEmailField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
